server:
  port: 8081
  servlet:
    context-path: /email

spring:
  application:
    name: email
  rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: william.cesar.santos1@gmail.com
    password: "*********"
    test-connection: true
    properties:
      mail:
        debug: true
        transport.protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

message:
  amqp:
    exchange: EMAIL_EXCHANGE
  queue:
    email:
      send: EMAIL_SENDER_QUEUE

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka
