server:
  port: 8081
  servlet:
    context-path: /task

spring:
  application:
    name: task
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/task?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spi
    password: spi
  rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest

message:
  amqp:
    exchange: TASK_EXCHANGE
  topic:
    late:
      task: LATE_TASK
    email:
      sender: EMAIL_SENDER

schedule:
  late:
    task: 10 * * * * ?
  notify:
    late:
      task: 10 * * * * ?
  send:
    email: 10 * * * * ?

security:
  jwt:
    token:
      secret-key: auth-jwt-test
      expire-length: 360000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka